# 配置文件加密根密码
jasypt:
  encryptor:
    password: chat #根密码
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

server:
  port: 9999

# Spring 相关
spring:
  application:
    name: @artifactId@
  boot:
    admin:
      client:
        # Spring Boot Admin 服务端地址
        url: "http://localhost:5001/"
        instance:
          metadata:
            # 客户端端点信息的安全认证信息
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(LvW9ulqQJxMYiMPo4c4X+g==) # root
    password: ENC(LXaP7OTcW1V/fijimCJT0zLZgh9o59Oj)
    url: jdbc:mysql://localhost:3306/chat_web?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
  cache:
    type: redis
  redis:
    host: localhost
    password: ENC(fDnzIsddShDIl0M2apLfBg==)
  rabbitmq:
    host: localhost
    port: 5672
    username: ENC(msCBv+Uv8/21qE1p+Acqhg==) # admin
    password: ENC(pSHCCpbOyq6+nhH6povIZQ==) # admin
    virtual-host: /
    # 手动提交消息
    listener:
      simple:
        acknowledge-mode: manual
      direct:
        acknowledge-mode: manual
  security:
    user:
      name: ENC(K24SXIYix81ef7ZQaWHgqQ==)     # admin
      password: ENC(T2bJImy7KWiM1QxT7X8lkA==) # admin

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# MyBaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

# spring security 配置
security:
  oauth2:
    # 通用放行URL，服务个性化，请在对应配置文件覆盖
    ignore:
      urls:
        - /v3/api-docs
        - /actuator/**
        - /code
        - /auth/oauth2/token

chat:
  encode-key: 'thanks,pig4cloud'
  ignore-clients:
    - test
    - client
  api-logging: false

# swagger 配置
#swagger:
#  enabled: true
#  title: Swagger API
#  gateway: http://${GATEWAY_HOST:chat-gateway}:${GATEWAY-PORT:9999}
#  token-url: ${swagger.gateway}/auth/oauth2/token
#  scope: server
#  services:
#    chat-upms-biz: admin
#    chat-web-biz: chat